### ISSUE TITLE
New build?

### ISSUE THREAD

**Issue by archiif** [ahodesuka/ahoviewer#106]
It's been almost 2 years since the last released build, would really appreciate a new one.

**Comment by ahodesuka** [comment]
I have yet to test ahoviewer thoroughly on Windows since the last build.
Setting up a build environment for Windows is an extreme pain in the ass for me, and debugging even more so.

**Comment by avail** [comment]
[msys](https://www.msys2.org/) might help with that

**Comment by ahodesuka** [comment]
A new version for Windows has been released (as a beta).
It's just a standalone version for now without an installer, but if you had the older version of ahoviewer installed you could just replace everything in the installation directory with the standalone version.
