### ISSUE TITLE
Skip Save Dialog

### ISSUE THREAD

**Issue by nihongodemilo** [ahodesuka/ahoviewer#107]
Is there a way to save a file bypassing the save dialog?  i.e. I press the shortcut key and it automatically saves to a predefined folder without prompting?

**Comment by ahodesuka** [comment]
Not currently, but it could be implemented as an option.

**Comment by ahodesuka** [comment]
Should be working now on master, note that you need to have `Remember last save path` option the booru browser options enabled.
The default keybinding is `shift+s`.
