### ISSUE TITLE
e621 doesn't work?

### ISSUE THREAD

**Issue by blissfulVoid** [ahodesuka/ahoviewer#115]
ahoviewer won't let me add it.
![2021-02-07_19-08](https://user-images.githubusercontent.com/75355637/107163515-c9ba1a00-69a1-11eb-9d32-3e15a99413a8.png)

**Comment by ahodesuka** [comment]
That booru doesn't seem to support an XML API, but provides a JSON one.
This could be supported with a plugin similar to what I created for [Sankaku](https://github.com/ahodesuka/ahoviewer-plugins/blob/master/sankakucomplex/sankakucomplex.py).

Gonna close this, and recommend you open a request issue over at [ahoviewer-plugins](https://github.com/ahodesuka/ahoviewer-plugins) repo.
