### ISSUE TITLE
Error while loading trumbnails

### ISSUE THREAD

**Issue by CumForMe** [ahodesuka/ahoviewer#116]
![2021-02-24-014940_2560x1439_scrot](https://user-images.githubusercontent.com/67879366/108929129-61bf3100-763b-11eb-8d52-2c1ed983a2bc.png)
Thumbnails don't seem to be loading properly, but the images load fine when they have actually been selected, this seems to be consistent across all boorus.

I am running Gentoo, and I use GCC for compilation.

**Comment by ahodesuka** [comment]
I'm unable to reproduce this issue as of right now.

**Comment by viperML** [comment]
Gentoo user too, and I had this exact error

Adding 'jpeg' to my global USE flags seemed to pull the dependencies needed to be fixed. E will try to find the exact the dependency and report the problem for the Ebuild.

**Comment by ahodesuka** [comment]
The jpeg use flag needs to be enabled for the gdk-pixbuf package.
