### ISSUE TITLE
Ability to delete an image

### ISSUE THREAD

**Issue by juippis** [ahodesuka/ahoviewer#119]
Hey, 

first of all thanks for the greatest image viewer!

As to the issue, I'd like a feature to delete an image we're currently browsing locally - or from the left pane. Right click, hotkey, through toolbar menu... doesn't matter. It's rather annoying having to locate the file from your disk again.

**Comment by ahodesuka** [comment]
By default this has a keybinding is `Shift+Delete`.  Confirmation
will be asked for before deleting.  An attempt will be made to move
the file to trash/recycle bin if supported, and if that fails the file
will be deleted permanently. The confirmation dialog can be turned 
off from the preferences dialog and from the confirmation dialog itself.

Deleting files from archives is not supported.

Also on Windows video files cannot be deleted while playing, 
gstreamer seems to have it actively open.

**Comment by juippis** [comment]
Thank you! Works like a charm.
