### ISSUE TITLE
Yande.re only showing thumbs, not full images

### ISSUE THREAD

**Issue by lurkser** [ahodesuka/ahoviewer#124]
Hello, I'm using ahoviewer 1.6.5-155-g87c98d3, and noticed that yande.re only shows the thumbnails on the sidebar, the full image never loads on the right side.

**Comment by ahodesuka** [comment]
Currently working for me on master (1.6.5-200-gc419695)

**Comment by lurkser** [comment]
Sorry, I forgot to say that I'm on Windows, also tried the latest nightly (ahoviewer-20210615-c41969-nightly-win64-standalone.zip) and still the same behavior.

**Comment by ahodesuka** [comment]
Just tested on Windows and it works fine for me there as well.  Does it work for you on their actual website?
Or try visiting [this API request ](https://yande.re/post.json?page=1&limit=50&tags=) and clicking on any of the file_url's
