### ISSUE TITLE
support for PNG files

### ISSUE THREAD

**Issue by plr20** [ahodesuka/ahoviewer#125]
Opening a ZIP file with bunch of PNGs doesn't work but JPGs do

**Comment by ahodesuka** [comment]
Do you have an example ZIP that I could use to reproduce this?

**Comment by plr20** [comment]
[Here(NSFW)](https://send.vis.ee/download/b1a2dff5106be439/#Z21lqwJa-2SbdCTye5FlLQ)

Sorry, didn't have any better examples that I had on me

**Comment by ahodesuka** [comment]
That particular ZIP file had something abnormal with its headers and was failing because I had the ZIP opening code performing stricter checks.  I turned off the strict checks, and the ZIP file now loads as expected.
