### ISSUE TITLE
No audio output for video files.

### ISSUE THREAD

**Issue by Jaspix** [ahodesuka/ahoviewer#132]
Whenever a video is playing there is no audio output.
Tested gstreamer audio output and seems to be doing well. 
I have installed it through AUR btw.

**Comment by ahodesuka** [comment]
By default the audiosink is set to `fakesink` which won't output any audio.
In the config file `~/.config/ahoviewer/ahoviewer.cfg` you need to add the following line `AudioSink = "autoaudiosink";`.
This should fix your problem.

Once I finish working on #120, sound should be enabled by default and there'll be a volume adjust widget.
