### ISSUE TITLE
Plugins in windows

### ISSUE THREAD

**Issue by Zeddylegend** [ahodesuka/ahoviewer#135]
Is there a way to install plugins in the windows version? i dont know much about this, sorry.

**Comment by ahodesuka** [comment]
The nightly Windows build from July 7th 2021 `ahoviewer-20210707-94be5a-nightly-win64-standalone.zip` found [here](https://github.com/ahodesuka/ahoviewer/releases/tag/nightly) supports plugins.
Plugins can be installed in 2 locations on Windows;
  - Inside a `plugins` directory in the root of the ahovewier directory (where the exe is)
  - Inside `%LOCALAPPDATA%\ahoviewer\plugins` (you'll have to create this directory yourself)

**Comment by Zeddylegend** [comment]
Thank you, but how can i install them? just copy and paste them into the plugins folder? i alredy did that with the sankaku one and i couldn't make it work :(

Also, Do you plan to implement searches with more than one booru at the same time? i know you can search in different tabs but it would be useful to search in multiple boorus at the same time like in booru slideshow for example.

Thanks :)

**Comment by ahodesuka** [comment]
Copy the .plugin and the .py file into a new directory inside the `plugins` directory, for example `%LOCALAPPDATA%\ahoviewer\plugins\sankaku`.
Then to add sakaku as a booru inside ahoviewer preferences window, use `https://capi-v2.sankakucomplex.com` as the URL, and it should come up as a valid booru.

>Also, Do you plan to implement searches with more than one booru at the same time? i know you can search in different tabs but it would be useful to search in multiple boorus at the same time like in booru slideshow for example.

This isn't something that I have thought of doing, but could be possible.  I'm more likely to rewrite this project in the future than add any major updates to the current code base as of right now though.
