### ISSUE TITLE
All video formats do not play (Arch)

### ISSUE THREAD

**Issue by saltmites** [ahodesuka/ahoviewer#142]
Hi, ahoviewer preview, images like gif all work, however any video format will display a thumbnail and the errorfile icon. The distribution I'm using is archlinux. Ahoviewer was installed using yay.

You can save the files, but opening those offline videos in ahoviewer still doesn't work.

I've checked the other issues about this, and I've tried the following fixes:

1. Installing all the dependencies listed in the aur page and github page (except libgsic++ I do see a package named as such)
2. Took a few tests on this issue https://github.com/ahodesuka/ahoviewer/issues/94
> GST_DEBUG=2 gst-play-1.0 <path to valid webm file>

> 0:00:00.016385204 13511 0x56041be57550 WARN                 basesrc gstbasesrc.c:3688:gst_base_src_start_complete:<source> pad not activated yet
> 0:00:00.016681926 13511 0x56041be57550 WARN                 basesrc gstbasesrc.c:3688:gst_base_src_start_complete:<source> pad not activated yet
> 0:00:00.035080788 13511 0x56041bf87360 WARN                 qtdemux qtdemux.c:3121:qtdemux_parse_trex:<qtdemux0> failed to find fragment defaults for stream 1
> 0:00:00.035200246 13511 0x56041bf87360 WARN                 qtdemux qtdemux.c:3121:qtdemux_parse_trex:<qtdemux0> failed to find fragment defaults for stream 2

There is a video output, no problems with that,

> gst-inspect-1.0 | grep -i "\(image\|video\)sink"

> autodetect:  autovideosink: Auto video sink
> debugutilsbad:  fakevideosink: Fake Video Sink
> debugutilsbad:  fpsdisplaysink: Measure and show framerate on videosink
> decklink:  decklinkvideosink: Decklink Video Sink
> inter:  intervideosink: Internal video sink
> opengl:  glimagesink: GL Sink Bin
> opengl:  glimagesinkelement: OpenGL video sink
> ximagesink:  ximagesink: Video sink
> xvimagesink:  xvimagesink: Video sink

3. Tried removing /usr/lib64/gstreamer-1.0/libgstxvimagesink.so (did not do a system reboot) and nothing happened. (I've restored it already)

I did not do any patches to gstreamer1.0-plugins-good described in that page, as the problem was specifically webm, which I do not suspect to help with my issue.

**Comment by ahodesuka** [comment]
This should fix the problem introduced in gstreamer 1.20
