### ISSUE TITLE
Gelbooru Search error.

### ISSUE THREAD

**Issue by zinkfrog** [ahodesuka/ahoviewer#146]
Whenever i try to load gelbooru I get the following error:
Search error: Please use your API key. Currently you have exceeded maximum queries per day. Yukkuri Shiteitte ne! :<

**Comment by Irets** [comment]
Can confirm.
I've made 0 queries today but am still met with that message.

**Comment by ahodesuka** [comment]
The fix requires you to have an account at gelbooru, and you'll need to add the api key to gelbooru in ahoviewer's settings.
Your API key can be found at the bottom of this page https://gelbooru.com/index.php?page=account&s=options when you're logged in.

Ahoviewer expects the entire string ie `&api_key=xxxx&user_id=xxxx`.

**Comment by ahodesuka** [comment]
> Now it works again without having an API key. Odd, but I'm not complaining.

Gelbooru does this sometimes when someones flooding their api.
