### ISSUE TITLE
surprise emoji picker  

### ISSUE THREAD

**Issue by Irets** [ahodesuka/ahoviewer#147]
Hi,
I just noticed that `CTRL+.` brings up an emoji picker, which feels really out of place in software like Ahoviewer.
Is this an intended feature? if so, for what purpose? Can the emoji picker be disabled? Or is this some mandatory cruft brought in by some library used by Ahoviewer?

![maim_1661596539](https://user-images.githubusercontent.com/50279814/187026628-47fc434d-4f79-45e1-b86b-cb3d09932c23.png)

I am using `1.6.5-233-gce4f2ab` commit of Ahoviewer on a Linux system.

**Comment by ahodesuka** [comment]
It's a built in default feature of GTK (the gui library ahoviewer uses).
Latest commit 42e16f94b78496e3e346f0d127baa569039a6757 should disable it as I agree it is useless for the search entry.
