### ISSUE TITLE
Question: Install help

### ISSUE THREAD

**Issue by wickedwzrd** [ahodesuka/ahoviewer#15]
I know it's sad but I can't figure out how to get your program running. I cloned the git and tried to find all the necessary dependencies but I couldn't install some of them. I installed gtkmm, glibmm and libconfig but I couldn't find libcurl and pugixml. I did install libcurlpp0 and libpugixml1 but I'm not sure if those are the right ones. I've tried to run the bootstrap file but it says autoreconf: not found. I still am fairly new to linux but if you could help me out with how to get your program running, I would great appreciate it.

**Comment by ahodesuka** [comment]
autoreconf is part of autotools. 
Since you didn't state your distro I'll just assume you're using Debian/Ubuntu.
Try installing automake and autoconf, and you'll also need a C++ compiler for this install build-essential.

**Comment by wickedwzrd** [comment]
Thanks I'll try this right away and get back to you. Also I'm trying to get it running on my mac first and foremost but if I cant get it to work on it, I am also trying to install it in Kubuntu.

**Comment by wickedwzrd** [comment]
I've installed everything you said to. Would I run bootstrap again with arguments or is there something else I need to do now?

**Comment by ahodesuka** [comment]
Do the following
```
./bootstrap
make
sudo make install
```

**Comment by wickedwzrd** [comment]
I ran into this error when I ran ./bootstrap:
./configure: line 4043: syntax error near unexpected token `,'
./configure: line 4043: `LIBCURL_CHECK_CONFIG(, 7.16.0,, AC_MSG_ERROR([libcurl >= 7.16.0 not found])

**Comment by ahodesuka** [comment]
Install libcurl4-openssl-dev instead of libcurlpp0, libcurlpp0 is not needed.

**Comment by wickedwzrd** [comment]
Thanks for that. Now I got to the point of pugixml.hpp not found. I have it downloaded and I built the project but I don't know where to put the folder so that the bootstrap will find it. Also sorry for the trouble

**Comment by ahodesuka** [comment]
Install libpugixml-dev

**Comment by wickedwzrd** [comment]
Ok I got that and did make and sudo make install. Now how do I run it. I went into src then clicked on ahoviewer to start it but how to I get it to run from command line.

**Comment by ahodesuka** [comment]
The installed executable should be in `/usr/local/bin`.
