### ISSUE TITLE
libnsgif-1.0.0 release renamed the header file

### ISSUE THREAD

**Issue by juippis** [ahodesuka/ahoviewer#153]
Hey,

upstream https://www.netsurf-browser.org/projects/libnsgif/ 1.0.0 renamed the header file from *libnsgif.h* to *nsgif.h* causing a breakage in ahoviewer.

```
fatal error: libnsgif.h: No such file or directory
    8 | #include <libnsgif.h>
      |          ^~~~~~~~~~~~
```

**Comment by Tuerai** [comment]
I am not sure how to do pull requests, but I got it to build doing this:
```
git clone https://github.com/ahodesuka/ahoviewer
cd ahoviewer/
sudo find ./ -type f -exec sed -i 's/libnsgif/nsgif/g' {} \;
mv ./ext/libnsgif/libnsgif.c ./ext/libnsgif/nsgif.c
mv ./ext/libnsgif/libnsgif.h ./ext/libnsgif/nsgif.h
mv ./ext/libnsgif ./ext/nsgif
meson setup build
cd build
sudo find ./ -type f -exec sed -i 's/libnsgif/nsgif/g' {} \;
ninja
sudo ninja install
```

**Comment by Irets** [comment]
I can confirm.
Gentoo Linux stabilized _libnsgif-1.0.0-r1_ on 2024-03-04 and for now I've masked the upgrade as the support is missing from Ahoviewer.
