### ISSUE TITLE
Windows version?

### ISSUE THREAD

**Issue by Decme** [ahodesuka/ahoviewer#16]
First, is it possible to install this on Windows, and second, can it be done with a simple zip or exe? I don't know how to compile from source.

**Comment by ahodesuka** [comment]
I'm currently working on cross-compiling ahoviewer for Windows, and it is almost ready for use.
There will probably be both a standalone (zip) and a installer version for Windows.

**Comment by Decme** [comment]
Awesome, will keep watch on this project, thanks for the update

**Comment by ahodesuka** [comment]
Starting with version 1.1.0 compiled Windows releases will be available.
As of now only the zip versions are being uploaded since I have not looked into making an installer.
