### ISSUE TITLE
Unable to Compile on OS X

### ISSUE THREAD

**Issue by YungArthur** [ahodesuka/ahoviewer#21]
I'm trying to compile this under OS X El Capitan, but I'm unable to due to an error regarding libcurl (which is installed).

```
./configure: line 3976: syntax error near unexpected token `,'
./configure: line 3976: `LIBCURL_CHECK_CONFIG(, 7.32.0,, AC_MSG_ERROR([libcurl >= 7.32.0 not found]))'
```

I have libcurl installed.
```
$ curl --version
curl 7.43.0 (x86_64-apple-darwin15.0) libcurl/7.43.0 SecureTransport zlib/1.2.5
```
I've tried setting the following environmental variables in hopes of resolving the issue, but no luck.
```
LDFLAGS=-L/usr/local/opt/curl/lib
CPPFLAGS=-I/usr/local/opt/curl/include
LIBCURL_CFLAGS=-I/usr/local/opt/curl/include
LIBCURL_LIBS=-L/usr/local/opt/curl/lib
```

Thanks!
P.S. I installed cURL through Homebrew.

**Comment by ahodesuka** [comment]
I updated the bootstrap script to work on OS X with libcurl installed through homebrew.
It does `./configure --with-libcurl=/usr/local/opt/curl` for you, so there is no need to set any environment variables.
