### ISSUE TITLE
Style

### ISSUE THREAD

**Issue by bordermick** [ahodesuka/ahoviewer#24]
I successfully installed ahoviewer in Arch Linux using the AUR but when I actually open it, the style has an ugly white to it. Is there a way so I can get it to look like your screenshot? This is what it looks like: http://i.imgur.com/QV74vOI.png

**Comment by adkow** [comment]
Ahoviewer uses GTK, so if you want to change its style there's no other option than installing other theme for GTK. However, I can't say what theme @ahodesuka is using.

**Comment by bordermick** [comment]
I am currently using Numix as my GTK theme with Gnome as my DE

**Comment by adkow** [comment]
Your ahoviewer looks like it should with Numix installed.
![numix___gtk3_theme_by_satya164-d5ygul6](https://cloud.githubusercontent.com/assets/14825909/12217716/370a9338-b709-11e5-8ebb-3dc64db1fa7d.jpg)

**Comment by bordermick** [comment]
Oh ok, that makes sense. In the Gnome tweak tool I enabled 'Global Dark Theme' so I assume that ahoviewer just isn't working with it. Is there any way that I can get that white to be dark?

**Comment by adkow** [comment]
I found @ahodesuka config in his dotfiles.
[ahodesuka/dotfiles/.gtkrc-2.0](https://github.com/ahodesuka/dotfiles/blob/master/.gtkrc-2.0)

It seems that he uses his own style.

>In the Gnome tweak tool I enabled 'Global Dark Theme' so I assume that ahoviewer just isn't working with it. Is there any way that I can get that white to be dark?

Can't tell as I don't use Gnome but I'm pretty sure that changing theme to the dark one will work.

**Comment by adkow** [comment]
Oh, wait. Here it is. You just have to download his theme and put this in .themes directory like here:
https://github.com/ahodesuka/dotfiles/tree/master/.themes/ahoka

**Comment by bordermick** [comment]
When I use the Ahoka theme it works fine, but I would like to keep using Numix if possible though. I tried disabling the 'Global Dark Theme' setting also, and it still looked the same as when I had it enabled, so im pretty sure its not taking effect on ahoviewer.

**Comment by ahodesuka** [comment]
>In the Gnome tweak tool I enabled 'Global Dark Theme'

This does not affect GTK2 applications.

After taking a look at the Numix theme - they do not include a dark variant for GTK2.
So you will need to find a dark variation of Numix's GTK2 theme,
here is one I found after a quick search: https://github.com/Steef435/Numix-dark

This is how it looks for me:
![2016-01-09-193242_997x905_scrot](https://cloud.githubusercontent.com/assets/1155344/12219411/c3b91a36-b707-11e5-9534-e436c759bf0c.png)

**Comment by bordermick** [comment]
This works! Thank you both so much for all the help :D
