### ISSUE TITLE
"Ahoviewer.exe has stopped working"

### ISSUE THREAD

**Issue by WychWitch** [ahodesuka/ahoviewer#25]
For some reason, whenever I try to use any of the booru viewers ahoviewer will crash upon the first search. I've tried launching in admin, entering my booru user and pass, and nothing has worked. I'm using windows 10 with 64 bit (of course) and I'm also using the 1.4.5 version

I can give more pc specs if needed

**Comment by ahodesuka** [comment]
Does this occur every time or is it random?

**Comment by BarrelTitor** [comment]
Yeah it occurs every single time without fail. It's odd, nothing i do seems to fix it. I've also tried disabling my antivi to see if that was interfering and that didn't help either

**Comment by ahodesuka** [comment]
Have you tried to run the program in Windows 7 compatibility mode?

**Comment by BarrelTitor** [comment]
Just tried, and nope does not work. Even tried windows 8 too

**Comment by carks32** [comment]
It's the same here on my end, W7 32bit, for some reason.
