### ISSUE TITLE
Can't compile it on Debian Jessie

### ISSUE THREAD

**Issue by 9Morello** [ahodesuka/ahoviewer#26]
Hello. I'm trying to compile it on Debian Jessie and I'm getting the following error:

"configure.ac:36: error: possibly undefined macro: AC_MSG_ERROR
      If this token and others are legitimate, please use m4_pattern_allow.
"

pkg-config is installed.

**Comment by NamcoPro** [comment]
I had the issue on Debian testing/stretch but managed to get by it with https://bbs.archlinux.org/viewtopic.php?id=161452.

**Comment by 1sean** [comment]
`configure.ac:36: error: possibly undefined macro: AC_MSG_ERROR`
`If this token and others are legitimate, please use m4_pattern_allow.`

run `dpkg-query -l | grep curl` to check your curl version, if it is `>= 7.32.0` then you should be able to just comment out line 36 in configure.ac

however once I got past that I ran into

`configure: error: Package requirements (libconfig++ >= 1.5) were not met:`
`Requested 'libconfig++ >= 1.5' but version of libconfig++ is 1.4.9`
`You may find new versions of libconfig++ at http://www.hyperrealm.com/main.php?s=libconfig`

you are going to need to complie libconfig from source, instructions on how to are at https://github.com/hyperrealm/libconfig

I also had to compile libxml2 from source but I don't think that is needed

**Comment by oliwer** [comment]
About the libconfig++ dependency, I just downgraded the requirement to version 1.4 and it works just fine using libconfig++ 1.4.9 on Ubuntu 14.04.
