### ISSUE TITLE
Random chance of crashing when viewing webms

### ISSUE THREAD

**Issue by keptan** [ahodesuka/ahoviewer#29]
When viewing local webms using Ahoviewer there is a high chance of a crash with the error: `ahoviewer: Fatal IO error 11 (Resource temporarily unavailable) on X server :0.0.`

It only happens when viewing webms, and occurs when selecting a webm from the sidebar. 
The crash isn't attached to certain webms, I can view the same webm it just crashed on in ahoviewer. 

running ahoviewer 1.4.5-5-g9b64c2d

**Comment by ahodesuka** [comment]
What version of gstreamer are you using?

**Comment by keptan** [comment]
`gstreamer-1.6.3-1`
I just did a reinstall just incase, and it still happens.

**Comment by ahodesuka** [comment]
I had random crashes with gstreamer 1.6, but never with 1.4.
I'll try to look for a way to resolve the issue, but for now I would recommend using 1.4 if you can.

**Comment by Ketchup901** [comment]
Can replicate this. Using gstreamer 1.10.2-1.

    ** (ahoviewer:13873): CRITICAL **: gst_gl_context_thread_add: assertion 'GST_IS_GL_CONTEXT (context)' failed
    Segmentation fault (core dumped)

Is using 1.4 still the recommended solution?

**Comment by ahodesuka** [comment]
Closing this, gstreamer 1.4.x or 1.10.4+ seems to be the functioning versions.
Better solution might be to just ditch gstreamer and use ffmpeg, but that would take a bit of work on my part.
