### ISSUE TITLE
file2string error during make

### ISSUE THREAD

**Issue by distcoll** [ahodesuka/ahoviewer#35]
While running the make command, I'm getting the following error:
`Usage: ./file2string infile outfile identifier`
I've determined that the command being run is:
`./file2string ui.cc ahoviewer_ui`
which causes errors because it only has two of three arguments. I haven't been able to figure out how to fix the make file.

**Comment by ahodesuka** [comment]
It should be running the following command:
`./file2string ui.glade ui.cc ahoviewer_ui`
Did you modify the `Makefile.am` file inside the src directory?

**Comment by distcoll** [comment]
I had not modified it. After hardcoding the Makefile.am line to
`./file2string ui.glade ui.cc ahoviewer_ui`
it did continue on to where it is now giving me an error that seems to be about an undefined reference to libconfig. I compiled libconfig from source so that I could have v1.5, maybe that's the problem?

**Comment by distcoll** [comment]
I managed to get it to work by installing libconfig 1.4.9 using my package manager (I'm on FreeBSD 10.2) and then continuing the make and then running make install. I can now run ahoviewer and it seems to work fine.
