### ISSUE TITLE
Dark theme for Windows

### ISSUE THREAD

**Issue by sonoshee-desu** [ahodesuka/ahoviewer#36]
Hi!
In ahoviewer for windows the left panel is of a white color. I wonder if we can get it to look like in [these screenshots](https://camo.githubusercontent.com/ad37a28fc1f47a41d1c79409ab31e3e01a1507e9/68747470733a2f2f692e696d6775722e636f6d2f486e47656368662e676966)

**Comment by ahodesuka** [comment]
GTK (ahoviewer UI library) uses your Windows theme.
On Windows 7 it works with custom themes, I am not sure about other Windows versions since I have not used them.
