### ISSUE TITLE
bootstrap does not work

### ISSUE THREAD

**Issue by Ketchup901** [ahodesuka/ahoviewer#37]
autoreconf: Entering directory .'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force 
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
configure.ac:36: error: possibly undefined macro: AC_MSG_ERROR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1

**Comment by ahodesuka** [comment]
Which OS is this?
This looks to be the same error found in #26

**Comment by Ketchup901** [comment]
Ubuntu 15.10

**Comment by DevYama** [comment]
Similar problem here. I'm on fedora 26.
My bootstrap ends on this. 
"configure: error: Package requirements (libconfig++ >= 1.5) were not met:
Package 'libconfig++', required by 'virtual:world', not found"

I have the latest libconfig++ installed.
"sudo dnf install libconfig++*
Last metadata expiration check: 0:56:14 ago on Fri 06 Oct 2017 11:47:18 AM EEST.
Package libconfig-1.5-5.fc26.x86_64 is already installed, skipping.
Dependencies resolved.
Nothing to do.
Complete!"

What to do?

**Comment by ahodesuka** [comment]
Check is `libconfig-devel` is installed.

**Comment by DevYama** [comment]
That did it! I don't see mention of it anywhere in dependencies though. :thinking: Should you add it?

**Comment by ahodesuka** [comment]
Dependency names vary from distro to distro.
Anything not marked as `runtime` is going to need the `-devel` variant in distros like Fedora.

**Comment by DevYama** [comment]
Oh! well "dnf install libconfig-devel" did it on fedora. Thank you!
(Also forgive if I sound dumb or something, I've been on linux since last summer.)
