### ISSUE TITLE
Memory hogs using the booru browser

### ISSUE THREAD

**Issue by NamcoPro** [ahodesuka/ahoviewer#38]
The tags listed a little over 700 images, I scrolled down to the bottom and used the save images option. It plowed through all 8GB of RAM and the 8GB of extra swap space. This is with a relatively small amount of images, I can't imagine what would happen with very popular tags.  I guess this isn't a common scenario, but I bet others save most images and then delete the ones they dislike.

This is also probably on my end, but browsing a directory with lots of images takes some time to startup, other viewers have no problem opening up an individual image in the unsorted mess.

**Comment by ahodesuka** [comment]
The issue when saving a large number of images should be easily fixable.

The load times when opening a directory with a large number of images I'll have to look into.
Around how many images or files are in the directory?

**Comment by NamcoPro** [comment]
The directory in question has over 18k files. I tried one with around half of it and the issue is still there albeit not as severe.
