### ISSUE TITLE
Assign multiple keybindings to same action

### ISSUE THREAD

**Issue by irlittz** [ahodesuka/ahoviewer#40]
Hey! First off: I really love ahoviewer, it comes very close to the comfiness I was used to when using Honeyview, except that ahoviewer even additionally supports *.webm files -- which is just awesome.

In Honeyview it was possible to assign multiple keybindings to the same action, for example I could assign the "next image" action to the space key, D and the right arrow key. Is this something you would consider adding?

**Comment by ahodesuka** [comment]
>Is this something you would consider adding?

I will look into whether this can be implemented.

**Comment by irlittz** [comment]
Thank you for the quick reply and your time!
