### ISSUE TITLE
Can't view\save webm files on Windows

### ISSUE THREAD

**Issue by UserNaem** [ahodesuka/ahoviewer#49]
Using ahoviewer 1.4.8 build from https://github.com/ahodesuka/ahoviewer/releases
Searched for "webm vocaloid -rating:explicit" on Gelbooru with API key entered.
After pressing "Save Image as..." the save dialog shows up, but after pressing "Save" it shows "Downloading 0 bytes \ (file size) @ 0 bytes\s" in the status bar and doesn't download anything. The same file can be viewed\saved in any other way (i.e. with mpv or any browser).

**Comment by Keith94** [comment]
Yeah, WebMs don't load at all for me, just blank screen.

**Comment by ahodesuka** [comment]
There is no webm support right now on Windows.

**Comment by Keith94** [comment]
Will it be added soon? Software looks great otherwise.

**Comment by ahodesuka** [comment]
>Will it be added soon? Software looks great otherwise.

It's not likely, but it's always possible.
