### ISSUE TITLE
Safebooru/Gelbooru no longer working

### ISSUE THREAD

**Issue by XenosisReaper** [ahodesuka/ahoviewer#50]
On 1.4.8 (windows)

I assume they altered their API since a few other things I use that pull from SB/GB are also a bit broken atm

**Comment by ahodesuka** [comment]
http://gelbooru.com/index.php?page=forum&s=view&id=3640
Seems like they've disabled the API as a temporary solution to someone abusing it.

**Comment by ahodesuka** [comment]
Looks like the api has been re-enabled for now.
