### ISSUE TITLE
** (ahoviewer:11791): CRITICAL **: gst_gl_context_thread_add: assertion 'GST_IS_GL_CONTEXT (context)' failed

### ISSUE THREAD

**Issue by cryzed** [ahodesuka/ahoviewer#51]
I'm using Arch Linux and since a recent system update this error appears when trying to play any webm and crashes ahoviewer completely. I also rebuilt ahoviewer to make sure it was unrelated to my current binary.

**Comment by ahodesuka** [comment]
My guess is it has something to do with newer version of gstreamer.  I noticed similar errors when using gstreamer-1.6

**Comment by cryzed** [comment]
I am using gstreamer 1.10.2, so that would support your theory. If I can give you anything more useful to fix the issue, let me know.

**Comment by ahodesuka** [comment]
I'll have to look and see if gstreamer has updated their documentation for what ever changes they made that are causing this.
I know that gstreamer versions 1.4.x did not have this problem.

**Comment by cryzed** [comment]
Alright, it would be appreciated when you find the time.

**Comment by Ketchup901** [comment]
Alright, using gstreamer 1.4 fixes the crashing issues but still won't play the files.
However, Clementine (the music player) will segfault unless you use a more recent version.

Can I suggest that while you try to find a way to fix this issue, you add a "tag blacklist" (or default tags) feature, so this can be avoided by simply disallowing any webm results from showing up?

**Comment by Tuerai** [comment]
Is there a way to sideload an old version of gstreamer and alias ahoviewer to always run with LD_PRELOAD or something to use the old version to avoid this bug until it's fixed?

**Comment by cryzed** [comment]
Webm files have magically started working for me again on Arch Linux, it's very likely related to the recent gstreamer (and related libraries) update from 1.10.3 to 1.10.4.
