### ISSUE TITLE
Issue #52 still present on windows (maybe)

### ISSUE THREAD

**Issue by connerst** [ahodesuka/ahoviewer#53]
With latest windows release, I have the same symptoms with safebooru(no thumbnails, no images). Since I have no clue how to run from terminal with log in windows, I cannot give solid evidence that this is the case, but the evidence suggests so.

**Comment by ahodesuka** [comment]
I'm aware.  I didn't have the time to make a new windows build with the latest changes.

**Comment by ahodesuka** [comment]
I built and uploaded a windows binary for 1.4.9 that includes the fix for this issue.
