### ISSUE TITLE
Add option to download with tags

### ISSUE THREAD

**Issue by ihavenoface** [ahodesuka/ahoviewer#58]
https://github.com/hydrusnetwork/hydrus offers a way to scrape a given directory for images periodically. 
Optionally it can pick up a text file containing the image tags, alongside the image, and import those as well.

ie. if you have an image called `myImage.png`, you could also put a corresponding text file called `myImage.png.txt` which holds the image's tags.

I think it would be very convenient to have an option which also stores the tags as described above.

**Comment by ahodesuka** [comment]
Option's disabled by default.

**Comment by ihavenoface** [comment]
Didn't even see that one. Thanks for having it implemented ahead of time then.

**Comment by ihavenoface** [comment]
Thanks!
