### ISSUE TITLE
Random crashes after loading ~10-20 images

### ISSUE THREAD

**Issue by Skvm** [ahodesuka/ahoviewer#59]
Experiencing a strange bug. Program randomly crashes after I load about 10-20 images properly. I can scroll for quite a while and load thumbnails with no problem, but when I click to load the full versions, the issue occurs.

Using the latest 1.4.9 release on Windows 8.1 Pro, have also tried running in compatibility mode with no success.

Windows error report:
  Problem Event Name:	APPCRASH
  Application Name:	ahoviewer.exe
  Application Version:	0.0.0.0
  Application Timestamp:	00000409
  Fault Module Name:	libgdkmm-2.4-1.dll
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	a500a4f0
  Exception Code:	c0000005
  Exception Offset:	000000000000d1d6
  OS Version:	6.3.9600.2.0.0.256.48
  Locale ID:	2057
  Additional Information 1:	09e7
  Additional Information 2:	09e72683f19e5f3e04a75545c7ddedf2
  Additional Information 3:	9db3
  Additional Information 4:	9db3eeb011fa9c097e5e9c2cab1b8b6c

**Comment by ahodesuka** [comment]
I've fixed a bunch of bugs over the past week, but haven't had time to test things on Windows yet so you'll have to wait a little bit before I release a new version that hopefully fixes this one.

**Comment by Skvm** [comment]
Awesome, I'll keep an eye out for the next release.
Thanks for the quick reply! Appreciate all your hard work.
