### ISSUE TITLE
Proxy settings ignored

### ISSUE THREAD

**Issue by UserNaem** [ahodesuka/ahoviewer#61]
ahoviewer seems to ignore any proxy settings on Windows, be it a proxy IP or an auto-configuration URL.
Some websites (including Danbooru and Gelbooru) are unavailable in my country, but [this proxy auto-configuration script](https://antizapret.prostovpn.org/proxy.pac) works. It's definitely not banned (as of right now), and I can view API pages like [this](https://gelbooru.com/index.php?page=dapi&s=post&q=index) in web browsers.

**Comment by ahodesuka** [comment]
From what I just read briefly you'll need to set the `http_proxy` and/or `https_proxy` environment variables for libcurl to use your proxy automatically.
Here's a simple guide on how to do that: https://docs.cloudfoundry.org/cf-cli/http-proxy.html#windows
Full proxy format looks like the following `http://username:password@proxy.example.com:8080`
Let me know if that works.

**Comment by UserNaem** [comment]
Yes, this appears to be working. My ISP randomly decided to let me access Gelbooru just now, but I was able to also access Danbooru after setting these environment variables (and break it again just to make sure). Thanks a lot. I think this will be a useful addition to readme\FAQ.

**Comment by ahodesuka** [comment]
Ok I just tried it in a virtual machine and setting both `http_proxy` and `https_proxy` to `proxy.antizapret.prostovpn.org:3128` seems to work.
