### ISSUE TITLE
WEBM not playing on Linux

### ISSUE THREAD

**Issue by funksh0n** [ahodesuka/ahoviewer#63]
I can visit the URL in browsers and it will play, I can download the file from ahoviewer and it will play (mplayer), but webms will not play inside ahoviewer.  I've tried multiple booru's, with and without login.

![2018-04-02-160608_1920x1080_scrot](https://user-images.githubusercontent.com/37955287/38201409-1b4d6856-3690-11e8-81d8-9d99670d432a.png)

**Comment by ahodesuka** [comment]
Are you sure you have these packages installed:
`gst-plugins-good`, and `gst-plugins-vpx` or `gst-plugins-libav`
The first is for demuxing the webm container, and the 2nd is for decoding the video.

**Comment by funksh0n** [comment]
Adding `gst-plugins-good` fixed it for me.  I installed from Arch Linux AUR.  Do you want me to contact the maintainer and ask them to make it a (suggested) requirement?

![udah](https://user-images.githubusercontent.com/37955287/38213205-4f567a8e-36b8-11e8-9440-613eac4ba147.png)
