### ISSUE TITLE
Support for Gelbooru 0.1.11?

### ISSUE THREAD

**Issue by Atulin** [ahodesuka/ahoviewer#65]
I was trying to add http://shorty.booru.org to the list of boorus, however it doesn't work, it shows a red X instead of a favicon, and isn't being shown in the search bar
![image](https://user-images.githubusercontent.com/11233299/42140035-0aeeab00-7d99-11e8-979e-7a495de3e55a.png)
![image](https://user-images.githubusercontent.com/11233299/42140037-11695f84-7d99-11e8-8c59-41a06a3bcf26.png)
The API isn't disabled, since ShortyBooru it works in a mobile app, Anime Boxes.

Using the newest, 1.5.0 version on Windows 10.

**Comment by ahodesuka** [comment]
Gelbooru 0.1.11 doesn't have any API functionality.
Anime Boxes most likely parses the html from the web front-end, and that is something ahoviewer isn't designed to do.
