### ISSUE TITLE
Program Stops opening

### ISSUE THREAD

**Issue by NO-ob** [ahodesuka/ahoviewer#66]
Hi I have encountered this issue about 3 times now and i'm not sure what causes it. When it happens the program will not open on screen, if you hover over the icon in task bar it show the preview as if it's open but does nothing on click. I have found the solution is deleting the .cfg in appdata but i have no idea what it's caused by as i don't mess with the default settings

**Comment by ahodesuka** [comment]
I've experienced this bug on Windows as well, and have been meaning to push a fix for it for a while.
I'll probably get something out soon and release a new version with this fixed.

**Comment by ahodesuka** [comment]
I figured out that this only occurs if you close the window while it is minimized.  I pushed a fix, but haven't released a new executable for Windows yet.
