### ISSUE TITLE
Translation support

### ISSUE THREAD

**Issue by emmauss** [ahodesuka/ahoviewer#72]
Can support be made to view translations of images is available?

**Comment by ahodesuka** [comment]
I'm not entirely sure this could be done in an elegant manor.
Notes including CSS would be impossible to mimic with GTK2, and even normal notes would be quite hard to find a nice way to be displayed.

My recommendation would be to just use the open post hotkey to view translated posts in your web browser.

**Comment by ahodesuka** [comment]
Gonna re-open this and look at possibly adding it as I'm now using GTK3 and it should be easier.

**Comment by ahodesuka** [comment]
Looking at this again and I just realized that neither danbooru or gelbooru expose translations with their API, so this isn't possible to be built into ahoviewer.
