### ISSUE TITLE
Can you only save jpgs in Konachan?

### ISSUE THREAD

**Issue by redcoatzygote** [ahodesuka/ahoviewer#79]
I've just downloaded the program today, and I have a couple questions.
1. Can you only view and download the the jpgs in ahoviewer Konachan? Most of the images come in both jpg and png (both in the same resolution and quality, png just being a larger file) and I usually only download the jpgs as they're smaller file sizes. Ahoviewer also always shows the png version if there's one available thus slowing down the loading when I could be viewing smaller jpgs. This isn't the case with Danbooru as all images only come in one image format as far as I know, so I believe the problem only occurs on Konachan.

2. This is really dumb but I'm having trouble themeing ahoviewer.
I've put `settings.ini`
```
[Settings]
gtk-font-name=lucy tewi 7
gtk-icon-theme-name=Arc
gtk-theme-name=Arc
```
in all `~/.config/gtk-2.0` and `/etc/gtk-2.0` and their 3.0 versions as well but that doesn't seem to change anything. The configs work as they theme my other GTK programs.
Thanks.

Edit: I'm using the latest AUR version of this package.

**Comment by ahodesuka** [comment]
1. I could add an option for this.  It could even be on a site-by-site basis.
2. Ahoviewer uses GTK2 so you'll have to make sure that you have the correct gtk2 theme installed.  You'll have to restart the program after changing the `settings.ini` or you could just try using lxappearance to manage your gtk themes.

**Comment by redcoatzygote** [comment]
>     1. I could add an option for this.  It could even be on a site-by-site basis.
> 
>     2. Ahoviewer uses GTK2 so you'll have to make sure that you have the correct gtk2 theme installed.  You'll have to restart the program after changing the `settings.ini` or you could just try using lxappearance to manage your gtk themes.

I would love it for you to implement that feature. I really only use ahoviewer for wallpaper browsing so if it could load images faster, that'd honestly make me continue using this booru viewer instead of the website.
Lxappearance works.
Thanks!

**Comment by ahodesuka** [comment]
Setting is disabled by default for all sites, so you'll have to enable the setting yourself for Konachan in the booru browser tab of the settings window.
I only tested it for a bit but it should be working correctly.

**Comment by redcoatzygote** [comment]
> Setting is disabled by default for all sites, so you'll have to enable the setting yourself for Konachan in the booru browser tab of the settings window.
> I only tested it for a bit but it should be working correctly.

Thanks a lot for doing this; browsing is much more fluent now. One last thing I've noticed:
![2019-03-03-170446_1920x1080_scrot](https://user-images.githubusercontent.com/47524677/53692166-9f837900-3dd6-11e9-98d6-290326225982.png)
Some of the images don't exist in ahoviewer when compared to Konachan's post page. Is this meant to be? There were no tags given and the maximum post rating was set to explicit.

**Comment by ahodesuka** [comment]
Should be fixed now.  Seemed to only affect moebooru based sites (konachan and yande.re)

**Comment by redcoatzygote** [comment]
> Should be fixed now. Seemed to only affect moebooru based sites (konachan and yande.re)

Hello again, the issue seems to have popped back up.
![2019-04-01-185229_1920x1080_scrot](https://user-images.githubusercontent.com/47524677/55315382-94903700-54af-11e9-9823-4bdd5772ebc3.png)
Maximum post rating is set to explicit, exactly the same as before.

**Comment by ahodesuka** [comment]
I actually think this is a bug? on their website.
If you look closely at the [post](https://konachan.com/post/show/281292) where it starts to differ it was uploaded 18 hours ago on their site, while the [post](https://konachan.com/post/show/280713) that shows up on their site in that spot was uploaded 12 days ago.

Also their homepage shows that there are a total of 222661 posts which matches what ahoviewer is displaying.

Their API and website are just ordering posts in a differently for what ever reason.

**Comment by redcoatzygote** [comment]
> I actually think this is a bug? on their website.
> If you look closely at the [post](https://konachan.com/post/show/281292) where it starts to differ it was uploaded 18 hours ago on their site, while the [post](https://konachan.com/post/show/280713) that shows up on their site in that spot was uploaded 12 days ago.
> 
> Also their homepage shows that there are a total of 222661 posts which matches what ahoviewer is displaying.
> 
> Their API and website are just ordering posts differently for what ever reason.

Ah, now it sure does seem like a bug on their end. Thanks.
