### ISSUE TITLE
Cannot open ahoviewer - symbol lookup error

### ISSUE THREAD

**Issue by catzybluphish** [ahodesuka/ahoviewer#81]
When I run `ahoviewer` from the terminal, it'll output `ahoviewer: symbol lookup error: /usr/lib/libgiomm-2.4.so.1: undefined symbol: g_dbus_connection_get_flags`. When I retried to build the AUR package, it now outputs
```
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1/../../../../lib/libgiomm-2.4.so: undefined reference to `g_app_info_launch_uris_async'
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1/../../../../lib/libgiomm-2.4.so: undefined reference to `g_dbus_connection_get_flags'
/usr/bin/ld: /usr/lib/gcc/x86_64-pc-linux-gnu/8.2.1/../../../../lib/libgiomm-2.4.so: undefined reference to `g_app_info_launch_uris_finish'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:506: ahoviewer] Error 1
make[2]: Leaving directory '/storage/ahoviewer-git/src/ahoviewer/src'
make[1]: *** [Makefile:375: all] Error 2
make[1]: Leaving directory '/storage/ahoviewer-git/src/ahoviewer/src'
make: *** [Makefile:434: all-recursive] Error 1
==> ERROR: A failure occurred in build().
    Aborting...
```
at the end of the compilation. Ahoviewer worked before, however. I've tried making it from this github repos but that didn't work either.
Thanks.

**Comment by ahodesuka** [comment]
I think your glibmm and glib package version are mismatched or something and causing the error.
What version of glib and glibmm do you have installed?

**Comment by catzybluphish** [comment]
> I think your glibmm and glib package version are mismatched or something and causing the error.
> What version of glib and glibmm do you have installed?

Yeah, located the problem which was the glib2 package. I'm using a [patched version](https://aur.archlinux.org/packages/glib2-patched-thumbnailer/) that allows the generation of thumbnails in the firefox filechooser. Ahoviewer works when I reinstall the normal glib2 package. However, I remember being able to open aho before with the patch from a last installation of Arch. Would you know anything about that?

**Comment by ahodesuka** [comment]
The thumbnail patch for glib itself isn't a problem, but if you're installing an older version of glib than what glibmm is that will cause a problem.
The version of glib cannot be older than that of glibmm or you'll run in to this type of problem where glibmm tries to look for functions that exist only in newer versions of glib.
