### ISSUE TITLE
Animated GIFs cause crashes

### ISSUE THREAD

**Issue by ahodesuka** [ahodesuka/ahoviewer#84]
This seems to occur only with the booru browser.

**Comment by jort93** [comment]
Animated gif's with the booru browser work on my windows 10 PC. (windows version 1809)

Seems to be a little more specific.  I am using a gtx 1660 Ti and ryzen 2600 if that helps.

**Comment by OrdinaryMagician** [comment]
I can consistently reproduce this on Linux. All I have to do is pretty much search the "gif" or "animated_gif" tags on any booru and it'll crash every time.

**Comment by ahodesuka** [comment]
@OrdinaryMagician Do local GIFs work?  Also a backtrace would be helpful.

**Comment by OrdinaryMagician** [comment]
OK this is annoying. I recompiled it so I could get debug symbols and now it stopped crashing.
