### ISSUE TITLE
No input for tag search in booru browser

### ISSUE THREAD

**Issue by FichteFoll** [ahodesuka/ahoviewer#85]
Built using latest commit on `master` on Arch Linux. There is no input for me to search for tags.

![2019-09-08_03-20-42](https://user-images.githubusercontent.com/931051/64482260-e40d2880-d1ee-11e9-9ac7-b6c1f4aa2b54.png)

**Comment by ahodesuka** [comment]
This tends to occur on the first launch of the application (when it downloads booru favicons specifically).
I've tried implementing some workarounds for it but they do not work 100%.
Try restarting the program, or resizing the booru browser and it should show up.

**Comment by FichteFoll** [comment]
I did resize it a couple times, but restarting helped.
