### ISSUE TITLE
Issue with Derpibooru

### ISSUE THREAD

**Issue by lk-KEVIN** [ahodesuka/ahoviewer#87]
I'm using the 1.6.5 version and trying to use [Derpibooru](https://derpibooru.org/) but doesn't recognize it like a Booru, but i've already use some of the default program sites before on this app [Booru Nav](https://play.google.com/store/apps/details?id=com.kinoshitaproductions.booru_nav) included Derpibooru
![booru](https://user-images.githubusercontent.com/25485634/75503167-eb91db00-59a2-11ea-9023-0b2de5b1b825.png)

**Comment by ahodesuka** [comment]
It seems derpibooru's "philomena" booru API only supports JSON, and ahoviewer relies on XML versions of danbooru/gelbooru/moebooru APIs.
Support for this could be added, but would require another dependency for handling JSON parsing.

**Comment by lk-KEVIN** [comment]
Thanks, I would love to see compatibility in the future with that page in case it have it
