### ISSUE TITLE
GTK3 branch segfault on start

### ISSUE THREAD

**Issue by Hubcapp** [ahodesuka/ahoviewer#90]
```
$ ./ahoviewer 

(ahoviewer:26279): Gtk-CRITICAL **: 06:49:51.399: gtk_label_set_text: assertion 'GTK_IS_LABEL (label)' failed
Segmentation fault
```
Not sure that this is helpful information, but that's my experience with the GTK3 branch. I'm using Debian 10.

<details>
<summary> <b>$ ./bootstrap && make && sudo make install</b> output
</summary>
<pre>
$ ./bootstrap && make && sudo make install
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force 
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --copy --force-missing
autoreconf: Leaving directory `.'
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking target system type... x86_64-pc-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of gcc... gcc3
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking whether g++ supports C++14 features by default... yes
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for glibmm... yes
checking for libsigcpp... yes
checking for gtkmm... yes
checking for libconfig... yes
checking for OpenSSL... yes
checking for gawk... (cached) gawk
checking for curl-config... /usr/bin/curl-config
checking for the version of libcurl... 7.64.0
checking for libcurl >= version 7.32.0... yes
checking whether libcurl is usable... yes
checking for curl_free... yes
checking for libxml2... yes
checking for libnsgif... no
checking for gstreamer... no
checking for libsecret... no
checking for unrar/dll.hpp... no
checking for libunrar/dll.hpp... no
checking for libzip... no
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating pixmaps/Makefile
config.status: creating po/Makefile
config.status: creating src/Makefile
config.status: creating src/config.h
config.status: src/config.h is unchanged
config.status: executing depfiles commands
Making all in pixmaps
make[1]: Entering directory '/home/tyler/code/notMine/ahoviewer/pixmaps'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/tyler/code/notMine/ahoviewer/pixmaps'
Making all in po
make[1]: Entering directory '/home/tyler/code/notMine/ahoviewer/po'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/tyler/code/notMine/ahoviewer/po'
Making all in src
make[1]: Entering directory '/home/tyler/code/notMine/ahoviewer/src'
make  all-am
make[2]: Entering directory '/home/tyler/code/notMine/ahoviewer/src'
  CXX      archive/ahoviewer-archive.o
  CXX      archive/ahoviewer-image.o
  CXX      archive/ahoviewer-rar.o
  CXX      archive/ahoviewer-zip.o
  CXX      booru/ahoviewer-browser.o
  CXX      booru/ahoviewer-curler.o
  CXX      booru/ahoviewer-image.o
  CXX      booru/ahoviewer-imagefetcher.o
  CXX      booru/ahoviewer-imagelist.o
  CXX      booru/ahoviewer-page.o
  CXX      booru/ahoviewer-site.o
  CXX      booru/ahoviewer-tagentry.o
  CXX      booru/ahoviewer-tagview.o
  CXX      ahoviewer-application.o
  CXX      ahoviewer-image.o
  CXX      ahoviewer-imagebox.o
  CXX      ahoviewer-imagelist.o
  CXX      ahoviewer-keybindingeditor.o
  CXX      ahoviewer-main.o
  CXX      ahoviewer-mainwindow.o
  CXX      ahoviewer-preferences.o
  CXX      ahoviewer-settings.o
  CXX      ahoviewer-siteeditor.o
  CXX      ahoviewer-statusbar.o
  CXX      ahoviewer-thumbnailbar.o
  CXX      ahoviewer-ui.o
  CXX      ahoviewer-version.o
  CC       ../ext/libnsgif/ahoviewer-libnsgif.o
  CC       ../ext/libnsgif/ahoviewer-lzw.o
  CXXLD    ahoviewer
make[2]: Leaving directory '/home/tyler/code/notMine/ahoviewer/src'
make[1]: Leaving directory '/home/tyler/code/notMine/ahoviewer/src'
make[1]: Entering directory '/home/tyler/code/notMine/ahoviewer'
make[1]: Nothing to be done for 'all-am'.
make[1]: Leaving directory '/home/tyler/code/notMine/ahoviewer'
Making install in pixmaps
make[1]: Entering directory '/home/tyler/code/notMine/ahoviewer/pixmaps'
make[2]: Entering directory '/home/tyler/code/notMine/ahoviewer/pixmaps'
make[2]: Nothing to be done for 'install-exec-am'.
 /bin/mkdir -p '/usr/local/share/pixmaps/ahoviewer'
 /usr/bin/install -c -m 644 ahoviewer-about-logo.png '/usr/local/share/pixmaps/ahoviewer'
 /bin/mkdir -p '/usr/local/share/icons/hicolor'
 /bin/mkdir -p '/usr/local/share/icons/hicolor/16x16/apps'
 /usr/bin/install -c -m 644  16x16/apps/ahoviewer.png '/usr/local/share/icons/hicolor/16x16/apps'
 /bin/mkdir -p '/usr/local/share/icons/hicolor/32x32/apps'
 /usr/bin/install -c -m 644  32x32/apps/ahoviewer.png '/usr/local/share/icons/hicolor/32x32/apps'
 /bin/mkdir -p '/usr/local/share/icons/hicolor/64x64/apps'
 /usr/bin/install -c -m 644  64x64/apps/ahoviewer.png '/usr/local/share/icons/hicolor/64x64/apps'
make[2]: Leaving directory '/home/tyler/code/notMine/ahoviewer/pixmaps'
make[1]: Leaving directory '/home/tyler/code/notMine/ahoviewer/pixmaps'
Making install in po
make[1]: Entering directory '/home/tyler/code/notMine/ahoviewer/po'
make[2]: Entering directory '/home/tyler/code/notMine/ahoviewer/po'
make[2]: Nothing to be done for 'install-exec-am'.
make[2]: Nothing to be done for 'install-data-am'.
make[2]: Leaving directory '/home/tyler/code/notMine/ahoviewer/po'
make[1]: Leaving directory '/home/tyler/code/notMine/ahoviewer/po'
Making install in src
make[1]: Entering directory '/home/tyler/code/notMine/ahoviewer/src'
make  install-am
make[2]: Entering directory '/home/tyler/code/notMine/ahoviewer/src'
make[3]: Entering directory '/home/tyler/code/notMine/ahoviewer/src'
 /bin/mkdir -p '/usr/local/bin'
  /usr/bin/install -c ahoviewer '/usr/local/bin'
make[3]: Nothing to be done for 'install-data-am'.
make[3]: Leaving directory '/home/tyler/code/notMine/ahoviewer/src'
make[2]: Leaving directory '/home/tyler/code/notMine/ahoviewer/src'
make[1]: Leaving directory '/home/tyler/code/notMine/ahoviewer/src'
make[1]: Entering directory '/home/tyler/code/notMine/ahoviewer'
make[2]: Entering directory '/home/tyler/code/notMine/ahoviewer'
make[2]: Nothing to be done for 'install-exec-am'.
 /bin/mkdir -p '/usr/local/share/applications'
 /usr/bin/install -c -m 644 ahoviewer.desktop '/usr/local/share/applications'
make[2]: Leaving directory '/home/tyler/code/notMine/ahoviewer'
make[1]: Leaving directory '/home/tyler/code/notMine/ahoviewer'
</pre>
</details>

**Comment by ahodesuka** [comment]
I had this issue on my laptop which was a fresh system, but randomly fixed it when I installed some package with a few dependencies (I should have noted which ones).
Running a backtrace I noticed it was occurring when the UI data was being loaded.
I'll try to figure it out and get back to you.

**Comment by ahodesuka** [comment]
Try e5b04ddad8a13ad3ad37d0127687d15fc519fecb and let me know if anything changes for you.

**Comment by Hubcapp** [comment]
That was it :+1:

**Comment by Hubcapp** [comment]
I would also like to report that nothing else immediately seems to be wrong.
