### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by botist** [ahodesuka/ahoviewer#92]
Is it a hidden option that I can't find? Or did you make it for your own personal use?

**Comment by ahodesuka** [comment]
Screenshot is shown using my gtk theme found here https://github.com/ahodesuka/dotfiles. (In the .themes directory)
If you're using Windows this won't work.

**Comment by botist** [comment]
I'm using WSL. How do I install your gtk theme completely? Including icons, cursor, toolbar, etc... I'm new to Linux stuff so this is giving me some trouble
