### ISSUE TITLE
How do I install your GTK theme?

### ISSUE THREAD

**Issue by botist** [ahodesuka/ahoviewer#93]
I'm new to Linux (took me a whole day to figure out how to install ahoviewer and its dependencies, along with all optional features) so idk about cool themes and yours looks good.

I managed to go dark mode by copying your .themes folder to home and selecting it using gnome-tweak, but after trying for some time I gave up on the other ones, like the toolbar, icons, cursor, etc. I now know my question isn't directly related to ahoviewer and I apologize for asking this as an issue here

**Comment by ahodesuka** [comment]
For my gtk2 theme you'll need the murrine theme engine installed (might already be installed).
I'm not sure what distro you're using but it should be available in just about all of them.
I updated my dotfiles with my icon theme (.icons directory), as well as an updated version of my theme for gtk3.
Cursor theme doesn't really matter, but I use openzone_fire.

If you need any other help not directly related to ahoviewer you can open an issue on my dotfiles repo.
