### ISSUE TITLE
Error rebuilding GTK3 branch today

### ISSUE THREAD

**Issue by pizzadude** [ahodesuka/ahoviewer#99]
After git pulling the latest changes and doing a rebuild of the GTK3 branch, Ahoviewer fails to build with this error:

```
/usr/bin/ld: ahoviewer-imagebox.o: undefined reference to symbol 'XFreeExtensionList'
/usr/bin/ld: /usr/lib64/libX11.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:548: ahoviewer] Error 1
```
This is on Fedora 32.
Any ideas?

**Comment by botist** [comment]
try building with meson

**Comment by ahodesuka** [comment]
Should work with meson, I haven't updated the autoconf files to reflect some recent changes.

**Comment by pizzadude** [comment]
Ok, it builds fine with meson. Thank you.
